language: node_js
node_js:
  - "node"
cache: npm
branches:
  only:
  - master
cache: npm
script:
  - npm run build

deploy:
  provider: pages
  local-dir: ./dist
  target-branch: gh-pages
  email: tksudharshan@gmail.com
  name: tks18
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
