os: linux

branches:
  only:
    - master

language: node_js

node_js:
  - 14

git:
  depth: 3
  quiet: true
  submodules: false

cache: yarn

script:
  - yarn build

deploy:
  provider: pages
  local-dir: ./dist
  target-branch: gh-pages
  email: tksudharshan@gmail.com
  name: tks18
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
