import { lettersArray } from '@t/emoji-array';

export default {
  someWords: {
    map: [
      lettersArray.indexOf('s'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('m'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('w'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('d'),
      lettersArray.indexOf('s'),
    ],
    initial: [1, 4, 5, 6, 2, 31, 33, 39, 5, 0],
  },
  title: {
    map: [
      lettersArray.indexOf('a'),
      lettersArray.indexOf('b'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('u'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('m'),
      lettersArray.indexOf('e'),
    ],
    initial: [20, 1, 3, 5, 6, 2, 39, 36],
  },
  hash: {
    initial: [
      lettersArray.indexOf('#'),
      lettersArray.indexOf('k'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('n'),
      lettersArray.indexOf('u'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('v'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('s'),
    ],
    map: [
      lettersArray.indexOf(' '),
      lettersArray.indexOf('#'),
      lettersArray.indexOf('j'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('h'),
      lettersArray.indexOf('n'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('w'),
      lettersArray.indexOf('i'),
      lettersArray.indexOf('c'),
      lettersArray.indexOf('k'),
      lettersArray.indexOf(' '),
    ],
  },
};
