import { lettersArray } from '@t/emoji-array';

export default {
  blog: {
    map: [
      lettersArray.indexOf('m'),
      lettersArray.indexOf('y'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('b'),
      lettersArray.indexOf('l'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('g'),
    ],
    initial: [46, 1, 3, 2, 40, 43, 10],
  },
  stories: {
    map: [
      lettersArray.indexOf('s'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('i'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('s'),
    ],
    initial: [40, 44, 42, 39, 41, 44, 2],
  },
  about: {
    map: [
      lettersArray.indexOf('a'),
      lettersArray.indexOf('b'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('u'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('m'),
      lettersArray.indexOf('e'),
    ],
    initial: [39, 41, 45, 43, 42, 44, 46, 38],
  },
  projtitle: {
    map: [
      lettersArray.indexOf('p'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('j'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('c'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf('s'),
    ],
    initial: [39, 41, 45, 43, 42, 44, 46, 38],
  },
  contactTitle: {
    map: [
      lettersArray.indexOf('g'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('l'),
      lettersArray.indexOf('l'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('y'),
    ],
    initial: [42, 46, 40, 1, 32, 45, 14],
  },
  feedBackTitle: {
    map: [
      lettersArray.indexOf('s'),
      lettersArray.indexOf('u'),
      lettersArray.indexOf('b'),
      lettersArray.indexOf('m'),
      lettersArray.indexOf('i'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('y'),
      lettersArray.indexOf('o'),
      lettersArray.indexOf('u'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('f'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('d'),
      lettersArray.indexOf('b'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('c'),
      lettersArray.indexOf('k'),
    ],
    initial: [
      42,
      46,
      40,
      1,
      32,
      45,
      14,
      42,
      46,
      40,
      1,
      32,
      45,
      14,
      42,
      46,
      40,
      1,
      32,
      45,
    ],
  },
  whatiDo: {
    map: [
      lettersArray.indexOf('w'),
      lettersArray.indexOf('h'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('t'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('i'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('d'),
      lettersArray.indexOf('o'),
    ],
    initial: [2, 20, 46, 40, 39, 27, 6, 42, 9],
  },
  gallerytitle: {
    map: [
      lettersArray.indexOf('g'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('l'),
      lettersArray.indexOf('l'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('r'),
      lettersArray.indexOf('y'),
    ],
    initial: [20, 1, 6, 7, 37, 33, 5],
  },
  spacextitle: {
    map: [
      lettersArray.indexOf('s'),
      lettersArray.indexOf('p'),
      lettersArray.indexOf('a'),
      lettersArray.indexOf('c'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('x'),
      lettersArray.indexOf(' '),
      lettersArray.indexOf('n'),
      lettersArray.indexOf('e'),
      lettersArray.indexOf('w'),
      lettersArray.indexOf('s'),
    ],
    initial: [1, 23, 39, 12, 11, 10, 23, 33, 35, 2, 20],
  },
};
