[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	baseUrl = "https://sudharshan.dev"

	sitemapPath = "/sitemap.xml"

	providers = [
		"google",
		"bing",
		"yandex"
	]